# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SODONNE8/Documents/GitHub/DIGITAL-SYSTEMS-DESIGN/LabA/tutorial code/project_A/project_A.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SODONNE8/Documents/GitHub/DIGITAL-SYSTEMS-DESIGN/LabA/tutorial code/project_A/project_A.gen/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/SODONNE8/Documents/GitHub/DIGITAL-SYSTEMS-DESIGN/LabA/tutorial code/project_A/project_A.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SODONNE8/Documents/GitHub/DIGITAL-SYSTEMS-DESIGN/LabA/tutorial code/project_A/project_A.gen/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
